### ISSUE TITLE
There's a Regular Expression Denial of Service vulnerability in the ansi-regex package in versions < 6.0.1:

### ISSUE THREAD

**Issue by prashant93** [chalk/strip-ansi#41]
The dependencies from this package that use out of date versions that I see are:
| -- strip-ansi@6.0.1 | -- ansi-regex@5.0.1

![image](https://user-images.githubusercontent.com/4151470/139227117-c1adb988-8958-4155-871c-aa8f830a4074.png)

Fix version is 6.0.1.

Team Can you please check this
As I have other packages they are also using strip-ansi version 6.0.1. As strip-anis version 7.0 using ESM and their pacakges
using CJS so it is difficult to update strip-ansi to version 7.
It would be great if strip-ansi@6.0.1 update their ansi-regex to version 6.0.1.

**Comment by NicolasCARPi** [comment]
These redos "vulnerabilities" need to stop. See this blog article: https://overreacted.io/npm-audit-broken-by-design/.

While @Qix- is right (it can be ignored), we are numerous with a CI pipeline analyzing vulns and it's always best to squash this instead of adding an exception. Note that for me `strip-ansi` comes from `eslint` which is an extremely popular package (20M/weekly dl) so your fix will be appreciated by many ;)

Cheers and thanks for your work!

**Comment by Qix-** [comment]
>  it's always best to squash this instead of adding an exception

If the vulnerability is still present in a recent version, then I agree with you. In this case, however, it is not. You should push `eslint` to update, or update `eslint` if you haven't already (assuming `eslint` has already updated).

I agree entirely with Dan Abramov here - the security audits in npm are also broken. It's not the first time npm rushed something out the door (`package-lock.json` was a nightmare when it was released and I'd pretty firmly argue it has absolutely zero value).

**Comment by NicolasCARPi** [comment]
> You should push eslint to update

Indeed, I thought I had the latest version but I'm two major versions behind! That's what you get when you don't update your JS dependencies for two days :p
